repo_root: /home/git/repos
admins:
  - noj
# Comment if you want to allow all git operations to all users.
project_check: ~/.gitsy/examples/access_check
# Uncomment if you want to use a template directory for new repositories.
#template_dir: ext/template
commands:
  info: 
    exec: ~/.gitsy/examples/info
    default: true
  moov_check:
    exec: ~/.gitsy/examples/moov_check
    admin_only: true
