dev:
  repo_root: /home/git/repos
  admins:
    - noj

  # Custom configs go here
  apollo: apollo.moovweb.com

prod:
  repo_root: /home/git/repos
  admins:
    - noj

  # Custom configs go here
  apollo: apollo-vc01-int
