dev:
  company: Moovweb
  repo_root: /home/git/repos
  project_check: apollo_check.rb
  admins:
    - noj
  # Uncomment if you want to use a template directory for new repositories.
  #template_dir: /home/git/template

prod:
  company: Moovweb
  repo_root: /home/git/repos
  project_check: apollo_check.rb
  admins:
    - noj
  # Uncomment if you want to use a template directory for new repositories.
  #template_dir: /home/git/template

